export const ADD = 'ADD'
export const MINUS = 'MINUS'
export const RESET_GOODS_AND_PRICE = 'RESET_GOODS_AND_PRICE' // 重置购物车
export const SET_USER_INFO = 'SET_USER_INFO' // 设置用户信息
export const ADD_GOODS = 'ADD_GOODS' // 添加商品
export const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE' // 设置商品总价
export const CHANGE_AUTH_TYPE = 'CHANGE_AUTH_TYPE' // 改变授权状态
export const SET_TRAIN_INFO = 'SET_TRAIN_INFO' // 保存车次信息
export const SET_USER_STATION = 'SET_USER_STATION' // 保存用户选择的站点信息
export const SET_TICKET_LIST = 'SET_TICKET_LIST' // 保存车次途径车站信息
